FROM node:14.17.6

# create working directory
WORKDIR /app

# copy package.json file and install to working directory
COPY ../package.json /app
RUN npm install

# copy all source code to working directory
COPY . /app

CMD [ "npm", "start" ]
